### ISSUE TITLE
As a user, I want an evergreen bookmarklet and basic page scrolling

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/browse#1]
## Overview
Let's create a evergreen bookmarklet that simply injects the latest `handsfree.js` and this projects custom plugins.

## Tasks
- [ ] Add Vuepress
- [ ] Create a plugin that adds vertical page scrolling
- [ ] Publish plugin to npm so that we can pull from CDN
- [ ] Create a bookmarklet button with instructions to drag to bookmark bar
- [ ] Host documentation site on Firebase
